### ISSUE TITLE
[Feature request] Music index swap

### ISSUE THREAD

**Issue by ArutanSipdrae** [TexTools/textools.github.io#1]
This was a feature from XIV explorer, which allow to reference the index of another music of the game for the music of our choosing, permitting things like changing trial mount music for any phase of said trial, or anything we want.
But now it's been discontinued and I think that would be a really nice feature to have on textools since it's all about moding the game.

**Comment by KoraLyn** [comment]
Closing this since it's not relevant to this repo and a [duplicate](https://github.com/TexTools/FFXIV_TexTools_UI/issues/26).
